// author: https://github.com/pabloFuente

using System;

namespace LiveKit.Rtc
{
    /// <summary>
    /// Represents a chat message in a room.
    /// </summary>
    public class ChatMessage
    {
        /// <summary>
        /// Gets the unique message ID.
        /// </summary>
        public string Id { get; }

        /// <summary>
        /// Gets the timestamp when the message was sent (milliseconds since epoch).
        /// </summary>
        public long Timestamp { get; }

        /// <summary>
        /// Gets the message text.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// Gets the timestamp when the message was last edited (if edited).
        /// </summary>
        public long? EditTimestamp { get; }

        /// <summary>
        /// Gets whether the message was generated by an AI/bot.
        /// </summary>
        public bool Generated { get; }

        /// <summary>
        /// Initializes a new chat message.
        /// </summary>
        /// <param name="id">The message ID.</param>
        /// <param name="timestamp">The timestamp in milliseconds.</param>
        /// <param name="message">The message text.</param>
        /// <param name="editTimestamp">Optional edit timestamp.</param>
        /// <param name="generated">Whether the message was AI-generated.</param>
        public ChatMessage(
            string id,
            long timestamp,
            string message,
            long? editTimestamp = null,
            bool generated = false
        )
        {
            Id = id ?? throw new ArgumentNullException(nameof(id));
            Timestamp = timestamp;
            Message = message ?? string.Empty;
            EditTimestamp = editTimestamp;
            Generated = generated;
        }

        /// <summary>
        /// Creates a ChatMessage from a proto message.
        /// </summary>
        internal static ChatMessage FromProto(LiveKit.Proto.ChatMessage proto)
        {
            return new ChatMessage(
                proto.Id,
                proto.Timestamp,
                proto.Message,
                proto.EditTimestamp > 0 ? (long?)proto.EditTimestamp : null,
                proto.Generated
            );
        }

        /// <summary>
        /// Converts to a proto message.
        /// </summary>
        internal LiveKit.Proto.ChatMessage ToProto()
        {
            var msg = new LiveKit.Proto.ChatMessage
            {
                Id = Id,
                Timestamp = Timestamp,
                Message = Message,
                Generated = Generated,
            };

            if (EditTimestamp.HasValue)
            {
                msg.EditTimestamp = EditTimestamp.Value;
            }

            return msg;
        }

        /// <summary>
        /// Gets the timestamp as a DateTime.
        /// </summary>
        public DateTime GetDateTime()
        {
            return DateTimeOffset.FromUnixTimeMilliseconds(Timestamp).DateTime;
        }

        /// <summary>
        /// Gets the edit timestamp as a DateTime (if available).
        /// </summary>
        public DateTime? GetEditDateTime()
        {
            if (!EditTimestamp.HasValue)
                return null;
            return DateTimeOffset.FromUnixTimeMilliseconds(EditTimestamp.Value).DateTime;
        }
    }
}
