// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: livekit_connector.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Livekit.Server.Sdk.Dotnet {

  /// <summary>Holder for reflection information generated from livekit_connector.proto</summary>
  public static partial class LivekitConnectorReflection {

    #region Descriptor
    /// <summary>File descriptor for livekit_connector.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitConnectorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdsaXZla2l0X2Nvbm5lY3Rvci5wcm90bxIHbGl2ZWtpdBogbGl2ZWtpdF9j",
            "b25uZWN0b3Jfd2hhdHNhcHAucHJvdG8aHmxpdmVraXRfY29ubmVjdG9yX3R3",
            "aWxpby5wcm90byo6Cg1Db25uZWN0b3JUeXBlEg8KC1Vuc3BlY2lmaWVkEAAS",
            "DAoIV2hhdHNBcHAQARIKCgZUd2lsaW8QAjLsAwoJQ29ubmVjdG9yElcKEERp",
            "YWxXaGF0c0FwcENhbGwSIC5saXZla2l0LkRpYWxXaGF0c0FwcENhbGxSZXF1",
            "ZXN0GiEubGl2ZWtpdC5EaWFsV2hhdHNBcHBDYWxsUmVzcG9uc2USaQoWRGlz",
            "Y29ubmVjdFdoYXRzQXBwQ2FsbBImLmxpdmVraXQuRGlzY29ubmVjdFdoYXRz",
            "QXBwQ2FsbFJlcXVlc3QaJy5saXZla2l0LkRpc2Nvbm5lY3RXaGF0c0FwcENh",
            "bGxSZXNwb25zZRJgChNDb25uZWN0V2hhdHNBcHBDYWxsEiMubGl2ZWtpdC5D",
            "b25uZWN0V2hhdHNBcHBDYWxsUmVxdWVzdBokLmxpdmVraXQuQ29ubmVjdFdo",
            "YXRzQXBwQ2FsbFJlc3BvbnNlEl0KEkFjY2VwdFdoYXRzQXBwQ2FsbBIiLmxp",
            "dmVraXQuQWNjZXB0V2hhdHNBcHBDYWxsUmVxdWVzdBojLmxpdmVraXQuQWNj",
            "ZXB0V2hhdHNBcHBDYWxsUmVzcG9uc2USWgoRQ29ubmVjdFR3aWxpb0NhbGwS",
            "IS5saXZla2l0LkNvbm5lY3RUd2lsaW9DYWxsUmVxdWVzdBoiLmxpdmVraXQu",
            "Q29ubmVjdFR3aWxpb0NhbGxSZXNwb25zZUJGWiNnaXRodWIuY29tL2xpdmVr",
            "aXQvcHJvdG9jb2wvbGl2ZWtpdKoCDUxpdmVLaXQuUHJvdG/qAg5MaXZlS2l0",
            "OjpQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Livekit.Server.Sdk.Dotnet.LivekitConnectorWhatsappReflection.Descriptor, global::Livekit.Server.Sdk.Dotnet.LivekitConnectorTwilioReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Livekit.Server.Sdk.Dotnet.ConnectorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ConnectorType {
    [pbr::OriginalName("Unspecified")] Unspecified = 0,
    [pbr::OriginalName("WhatsApp")] WhatsApp = 1,
    [pbr::OriginalName("Twilio")] Twilio = 2,
  }

  #endregion

}

#endregion Designer generated code
