// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: livekit_token_source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Livekit.Server.Sdk.Dotnet {

  /// <summary>Holder for reflection information generated from livekit_token_source.proto</summary>
  public static partial class LivekitTokenSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for livekit_token_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitTokenSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpsaXZla2l0X3Rva2VuX3NvdXJjZS5wcm90bxIHbGl2ZWtpdBoSbGl2ZWtp",
            "dF9yb29tLnByb3RvIsIDChJUb2tlblNvdXJjZVJlcXVlc3QSFgoJcm9vbV9u",
            "YW1lGAEgASgJSACIAQESHQoQcGFydGljaXBhbnRfbmFtZRgCIAEoCUgBiAEB",
            "EiEKFHBhcnRpY2lwYW50X2lkZW50aXR5GAMgASgJSAKIAQESIQoUcGFydGlj",
            "aXBhbnRfbWV0YWRhdGEYBCABKAlIA4gBARJWChZwYXJ0aWNpcGFudF9hdHRy",
            "aWJ1dGVzGAUgAygLMjYubGl2ZWtpdC5Ub2tlblNvdXJjZVJlcXVlc3QuUGFy",
            "dGljaXBhbnRBdHRyaWJ1dGVzRW50cnkSNAoLcm9vbV9jb25maWcYBiABKAsy",
            "Gi5saXZla2l0LlJvb21Db25maWd1cmF0aW9uSASIAQEaPAoaUGFydGljaXBh",
            "bnRBdHRyaWJ1dGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJ",
            "OgI4AUIMCgpfcm9vbV9uYW1lQhMKEV9wYXJ0aWNpcGFudF9uYW1lQhcKFV9w",
            "YXJ0aWNpcGFudF9pZGVudGl0eUIXChVfcGFydGljaXBhbnRfbWV0YWRhdGFC",
            "DgoMX3Jvb21fY29uZmlnIkQKE1Rva2VuU291cmNlUmVzcG9uc2USEgoKc2Vy",
            "dmVyX3VybBgBIAEoCRIZChFwYXJ0aWNpcGFudF90b2tlbhgCIAEoCUJGWiNn",
            "aXRodWIuY29tL2xpdmVraXQvcHJvdG9jb2wvbGl2ZWtpdKoCDUxpdmVLaXQu",
            "UHJvdG/qAg5MaXZlS2l0OjpQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Livekit.Server.Sdk.Dotnet.LivekitRoomReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Server.Sdk.Dotnet.TokenSourceRequest), global::Livekit.Server.Sdk.Dotnet.TokenSourceRequest.Parser, new[]{ "RoomName", "ParticipantName", "ParticipantIdentity", "ParticipantMetadata", "ParticipantAttributes", "RoomConfig" }, new[]{ "RoomName", "ParticipantName", "ParticipantIdentity", "ParticipantMetadata", "RoomConfig" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Server.Sdk.Dotnet.TokenSourceResponse), global::Livekit.Server.Sdk.Dotnet.TokenSourceResponse.Parser, new[]{ "ServerUrl", "ParticipantToken" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TokenSourceRequest : pb::IMessage<TokenSourceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TokenSourceRequest> _parser = new pb::MessageParser<TokenSourceRequest>(() => new TokenSourceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TokenSourceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Server.Sdk.Dotnet.LivekitTokenSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceRequest(TokenSourceRequest other) : this() {
      roomName_ = other.roomName_;
      participantName_ = other.participantName_;
      participantIdentity_ = other.participantIdentity_;
      participantMetadata_ = other.participantMetadata_;
      participantAttributes_ = other.participantAttributes_.Clone();
      roomConfig_ = other.roomConfig_ != null ? other.roomConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceRequest Clone() {
      return new TokenSourceRequest(this);
    }

    /// <summary>Field number for the "room_name" field.</summary>
    public const int RoomNameFieldNumber = 1;
    private string roomName_;
    /// <summary>
    /// The name of the room being requested when generating credentials
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomName {
      get { return roomName_ ?? ""; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "room_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRoomName {
      get { return roomName_ != null; }
    }
    /// <summary>Clears the value of the "room_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRoomName() {
      roomName_ = null;
    }

    /// <summary>Field number for the "participant_name" field.</summary>
    public const int ParticipantNameFieldNumber = 2;
    private string participantName_;
    /// <summary>
    /// The name of the participant being requested for this client when generating credentials
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantName {
      get { return participantName_ ?? ""; }
      set {
        participantName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "participant_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasParticipantName {
      get { return participantName_ != null; }
    }
    /// <summary>Clears the value of the "participant_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParticipantName() {
      participantName_ = null;
    }

    /// <summary>Field number for the "participant_identity" field.</summary>
    public const int ParticipantIdentityFieldNumber = 3;
    private string participantIdentity_;
    /// <summary>
    /// The identity of the participant being requested for this client when generating credentials
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantIdentity {
      get { return participantIdentity_ ?? ""; }
      set {
        participantIdentity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "participant_identity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasParticipantIdentity {
      get { return participantIdentity_ != null; }
    }
    /// <summary>Clears the value of the "participant_identity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParticipantIdentity() {
      participantIdentity_ = null;
    }

    /// <summary>Field number for the "participant_metadata" field.</summary>
    public const int ParticipantMetadataFieldNumber = 4;
    private string participantMetadata_;
    /// <summary>
    /// Any participant metadata being included along with the credentials generation operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantMetadata {
      get { return participantMetadata_ ?? ""; }
      set {
        participantMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "participant_metadata" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasParticipantMetadata {
      get { return participantMetadata_ != null; }
    }
    /// <summary>Clears the value of the "participant_metadata" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParticipantMetadata() {
      participantMetadata_ = null;
    }

    /// <summary>Field number for the "participant_attributes" field.</summary>
    public const int ParticipantAttributesFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_participantAttributes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> participantAttributes_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Any participant attributes being included along with the credentials generation operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> ParticipantAttributes {
      get { return participantAttributes_; }
    }

    /// <summary>Field number for the "room_config" field.</summary>
    public const int RoomConfigFieldNumber = 6;
    private global::Livekit.Server.Sdk.Dotnet.RoomConfiguration roomConfig_;
    /// <summary>
    /// A RoomConfiguration object can be passed to request extra parameters should be included when
    /// generating connection credentials - dispatching agents, defining egress settings, etc
    /// More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Server.Sdk.Dotnet.RoomConfiguration RoomConfig {
      get { return roomConfig_; }
      set {
        roomConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TokenSourceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TokenSourceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomName != other.RoomName) return false;
      if (ParticipantName != other.ParticipantName) return false;
      if (ParticipantIdentity != other.ParticipantIdentity) return false;
      if (ParticipantMetadata != other.ParticipantMetadata) return false;
      if (!ParticipantAttributes.Equals(other.ParticipantAttributes)) return false;
      if (!object.Equals(RoomConfig, other.RoomConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRoomName) hash ^= RoomName.GetHashCode();
      if (HasParticipantName) hash ^= ParticipantName.GetHashCode();
      if (HasParticipantIdentity) hash ^= ParticipantIdentity.GetHashCode();
      if (HasParticipantMetadata) hash ^= ParticipantMetadata.GetHashCode();
      hash ^= ParticipantAttributes.GetHashCode();
      if (roomConfig_ != null) hash ^= RoomConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRoomName) {
        output.WriteRawTag(10);
        output.WriteString(RoomName);
      }
      if (HasParticipantName) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantName);
      }
      if (HasParticipantIdentity) {
        output.WriteRawTag(26);
        output.WriteString(ParticipantIdentity);
      }
      if (HasParticipantMetadata) {
        output.WriteRawTag(34);
        output.WriteString(ParticipantMetadata);
      }
      participantAttributes_.WriteTo(output, _map_participantAttributes_codec);
      if (roomConfig_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(RoomConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRoomName) {
        output.WriteRawTag(10);
        output.WriteString(RoomName);
      }
      if (HasParticipantName) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantName);
      }
      if (HasParticipantIdentity) {
        output.WriteRawTag(26);
        output.WriteString(ParticipantIdentity);
      }
      if (HasParticipantMetadata) {
        output.WriteRawTag(34);
        output.WriteString(ParticipantMetadata);
      }
      participantAttributes_.WriteTo(ref output, _map_participantAttributes_codec);
      if (roomConfig_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(RoomConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRoomName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      if (HasParticipantName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantName);
      }
      if (HasParticipantIdentity) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantIdentity);
      }
      if (HasParticipantMetadata) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantMetadata);
      }
      size += participantAttributes_.CalculateSize(_map_participantAttributes_codec);
      if (roomConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TokenSourceRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasRoomName) {
        RoomName = other.RoomName;
      }
      if (other.HasParticipantName) {
        ParticipantName = other.ParticipantName;
      }
      if (other.HasParticipantIdentity) {
        ParticipantIdentity = other.ParticipantIdentity;
      }
      if (other.HasParticipantMetadata) {
        ParticipantMetadata = other.ParticipantMetadata;
      }
      participantAttributes_.Add(other.participantAttributes_);
      if (other.roomConfig_ != null) {
        if (roomConfig_ == null) {
          RoomConfig = new global::Livekit.Server.Sdk.Dotnet.RoomConfiguration();
        }
        RoomConfig.MergeFrom(other.RoomConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoomName = input.ReadString();
            break;
          }
          case 18: {
            ParticipantName = input.ReadString();
            break;
          }
          case 26: {
            ParticipantIdentity = input.ReadString();
            break;
          }
          case 34: {
            ParticipantMetadata = input.ReadString();
            break;
          }
          case 42: {
            participantAttributes_.AddEntriesFrom(input, _map_participantAttributes_codec);
            break;
          }
          case 50: {
            if (roomConfig_ == null) {
              RoomConfig = new global::Livekit.Server.Sdk.Dotnet.RoomConfiguration();
            }
            input.ReadMessage(RoomConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RoomName = input.ReadString();
            break;
          }
          case 18: {
            ParticipantName = input.ReadString();
            break;
          }
          case 26: {
            ParticipantIdentity = input.ReadString();
            break;
          }
          case 34: {
            ParticipantMetadata = input.ReadString();
            break;
          }
          case 42: {
            participantAttributes_.AddEntriesFrom(ref input, _map_participantAttributes_codec);
            break;
          }
          case 50: {
            if (roomConfig_ == null) {
              RoomConfig = new global::Livekit.Server.Sdk.Dotnet.RoomConfiguration();
            }
            input.ReadMessage(RoomConfig);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TokenSourceResponse : pb::IMessage<TokenSourceResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TokenSourceResponse> _parser = new pb::MessageParser<TokenSourceResponse>(() => new TokenSourceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TokenSourceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Server.Sdk.Dotnet.LivekitTokenSourceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceResponse(TokenSourceResponse other) : this() {
      serverUrl_ = other.serverUrl_;
      participantToken_ = other.participantToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TokenSourceResponse Clone() {
      return new TokenSourceResponse(this);
    }

    /// <summary>Field number for the "server_url" field.</summary>
    public const int ServerUrlFieldNumber = 1;
    private string serverUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerUrl {
      get { return serverUrl_; }
      set {
        serverUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant_token" field.</summary>
    public const int ParticipantTokenFieldNumber = 2;
    private string participantToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantToken {
      get { return participantToken_; }
      set {
        participantToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TokenSourceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TokenSourceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerUrl != other.ServerUrl) return false;
      if (ParticipantToken != other.ParticipantToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerUrl.Length != 0) hash ^= ServerUrl.GetHashCode();
      if (ParticipantToken.Length != 0) hash ^= ParticipantToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServerUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerUrl);
      }
      if (ParticipantToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServerUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerUrl);
      }
      if (ParticipantToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ServerUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerUrl);
      }
      if (ParticipantToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TokenSourceResponse other) {
      if (other == null) {
        return;
      }
      if (other.ServerUrl.Length != 0) {
        ServerUrl = other.ServerUrl;
      }
      if (other.ParticipantToken.Length != 0) {
        ParticipantToken = other.ParticipantToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerUrl = input.ReadString();
            break;
          }
          case 18: {
            ParticipantToken = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServerUrl = input.ReadString();
            break;
          }
          case 18: {
            ParticipantToken = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
