// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: logger/options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Livekit.Server.Sdk.Dotnet {

  /// <summary>Holder for reflection information generated from logger/options.proto</summary>
  public static partial class OptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for logger/options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRsb2dnZXIvb3B0aW9ucy5wcm90bxIGbG9nZ2VyGiBnb29nbGUvcHJvdG9i",
            "dWYvZGVzY3JpcHRvci5wcm90bypXCgtTZW5zaXRpdml0eRIbChdTRU5TSVRJ",
            "VklUWV9VTlNQRUNJRklFRBAAEhMKD1NFTlNJVElWSVRZX1BJSRABEhYKElNF",
            "TlNJVElWSVRZX1NFQ1JFVBACOjUKDXJlZGFjdF9mb3JtYXQSHS5nb29nbGUu",
            "cHJvdG9idWYuRmllbGRPcHRpb25zGIYKIAEoCTosCgRuYW1lEh0uZ29vZ2xl",
            "LnByb3RvYnVmLkZpZWxkT3B0aW9ucxiHCiABKAk6SAoLc2Vuc2l0aXZpdHkS",
            "HS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGIgKIAEoDjITLmxvZ2dl",
            "ci5TZW5zaXRpdml0eUJNWipnaXRodWIuY29tL2xpdmVraXQvcHJvdG9jb2wv",
            "bGl2ZWtpdC9sb2dnZXKqAg1MaXZlS2l0LlByb3Rv6gIOTGl2ZUtpdDo6UHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Livekit.Server.Sdk.Dotnet.Sensitivity), }, new pb::Extension[] { OptionsExtensions.RedactFormat, OptionsExtensions.Name, OptionsExtensions.Sensitivity }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of logger/options.proto</summary>
  public static partial class OptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> RedactFormat =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(1286, pb::FieldCodec.ForString(10290, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Name =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(1287, pb::FieldCodec.ForString(10298, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Livekit.Server.Sdk.Dotnet.Sensitivity> Sensitivity =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Livekit.Server.Sdk.Dotnet.Sensitivity>(1288, pb::FieldCodec.ForEnum(10304, x => (int) x, x => (global::Livekit.Server.Sdk.Dotnet.Sensitivity) x, global::Livekit.Server.Sdk.Dotnet.Sensitivity.Unspecified));
  }

  #region Enums
  public enum Sensitivity {
    /// <summary>
    /// Unannotated default — safe to log.
    /// Identifiers, IDs, timestamps, enums, status fields.
    /// </summary>
    [pbr::OriginalName("SENSITIVITY_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// User-identifying or user-controlled data: display names, phone numbers,
    /// metadata, attributes, custom headers, auth usernames, semi-public account
    /// identifiers (AWS role ARNs, Azure account names).
    /// Redacted by logger.Proto(); exposed by logger.UnredactedProto() for
    /// operator-facing observability events.
    /// </summary>
    [pbr::OriginalName("SENSITIVITY_PII")] Pii = 1,
    /// <summary>
    /// Credentials and authentication material: passwords, access keys, session
    /// tokens, signing keys, API keys, ICE credentials.
    /// ALWAYS redacted, including by logger.UnredactedProto().
    /// </summary>
    [pbr::OriginalName("SENSITIVITY_SECRET")] Secret = 2,
  }

  #endregion

}

#endregion Designer generated code
