// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: logger/options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Livekit.Server.Sdk.Dotnet {

  /// <summary>Holder for reflection information generated from logger/options.proto</summary>
  public static partial class OptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for logger/options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRsb2dnZXIvb3B0aW9ucy5wcm90bxIGbG9nZ2VyGiBnb29nbGUvcHJvdG9i",
            "dWYvZGVzY3JpcHRvci5wcm90bzovCgZyZWRhY3QSHS5nb29nbGUucHJvdG9i",
            "dWYuRmllbGRPcHRpb25zGMHNBSABKAg6NgoNcmVkYWN0X2Zvcm1hdBIdLmdv",
            "b2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYws0FIAEoCTotCgRuYW1lEh0u",
            "Z29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjDzQUgASgJQk1aKmdpdGh1",
            "Yi5jb20vbGl2ZWtpdC9wcm90b2NvbC9saXZla2l0L2xvZ2dlcqoCDUxpdmVL",
            "aXQuUHJvdG/qAg5MaXZlS2l0OjpQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionsExtensions.Redact, OptionsExtensions.RedactFormat, OptionsExtensions.Name }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of logger/options.proto</summary>
  public static partial class OptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> Redact =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(91841, pb::FieldCodec.ForBool(734728, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> RedactFormat =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(91842, pb::FieldCodec.ForString(734738, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Name =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(91843, pb::FieldCodec.ForString(734746, ""));
  }

}

#endregion Designer generated code
